== Determining sensitivity

As a first step, information holders need to identify any data which are regarded as ‘<<sensitive-data,sensitive>>’. Sensitive information is any which if released to the public, would result in an ‘adverse effect’ on the taxon or attribute in question or to a living individual. A number of factors need to be taken into account when determining sensitivity, including the type and level of threat, vulnerability of the taxon or attribute, type of information, and whether it is already publicly available. Determining these factors leads us to a criteria-based approach.

Information cannot be considered sensitive if it is readily available through other sources or if it is not unique. This principle has been identified in a number of sensitive data policies (http://publications.gc.ca/collections/collection_2011/rncan-nrcan/M104-4-2010-eng.pdf[AMEC Earth and Environmental 2010^], https://www.environment.gov.au/system/files/resources/246e674a-feb1-4399-a678-be9f4b6a6800/files/sensitive-ecological-data-access-mgt-policy.pdf[Australian Government 2016^]).

It would appear that herbaria are more inclined to restrict their data than mammal or insect collections (https://doi.org/10.35035/vs84-0p13[Chapman 2006^]). Perhaps this is because plants don’t move and the exact location of a collection is likely to lead one to an actual plant on the ground, whereas mammals and insects tend to move around. One entomologist commented that professional collectors and amateur groups often know more than the scientists about the location of rare species. However there are categories of animals where the exact locations were thought to be sensitive and included bat roosting and maternity sites, nesting sites of falcons, and the location of various lizards, tortoise, butterfly species and large mammals. With plants, there is also a strong leaning towards not making information available for plants likely to be collected (pirated) such as cacti in Arizona, orchids and cycads. The protection of sensitive fossil sites was also identified. One unfortunate aspect is the susceptibility of a small number of taxa in a group (such as a few charismatic cacti, or orchids, etc.) can often mean that all taxa in that group are then regarded as sensitive and the data on them restricted, even though many of those taxa are not themselves sensitive or susceptible to harmful acts.

On the other hand, some institutions have found benefit in working with the general public to gather information and to protect rare taxa, using the public and special interest groups to survey existing locations and to help locate new locations. There are good examples with birds, lizards, frogs, butterflies and various plant species (including orchids) in a number of countries. Several people have raised the issue of the balance between protecting taxa through knowledge of where they occur as opposed to protection through restricting knowledge of their occurrence at a location. This is very taxon (and maybe region) specific and certain taxa may be in greater danger due to inadvertent destruction through lack of knowledge than through deliberate collection and destruction through knowledge of locations. For this reason, a list of sensitive taxa should be quite different to a list of rare or threatened taxa, although there is likely to be considerable overlap between the two. It should be noted, also, that what is sensitive today, may not be sensitive tomorrow and vice versa and this should lead to review on a periodic basis to determine whether the context has changed over time (http://publications.gc.ca/collections/collection_2011/rncan-nrcan/M104-4-2010-eng.pdf[AMEC Earth and Environmental 2010^]).

As noted in an article in _Science_ (https://doi.org/10.1126/science.312.5777.1137b[Stuart et al. 2006^]), three newly discovered amphibian and reptile species rapidly appeared in commercial trade shortly after their descriptions in the scientific literature. This is an issue of concern to biologists and especially to taxonomists (https://www.chronicle.com/article/Endangered-by-Research/26117[Guterman 2006^]) – how much information should be released in publication when describing a new taxon. There are a number of examples in coral-reef fish where a new species has appeared in the commercial trade soon after it is scientifically described.

[quote,Richard Pyle,personal communication 2006]
____
A few examples with which I have had direct experience include _Centropyge boylei_, _Centropyge narcosis_ [and] _Belonoperce pylei_…among a number of others.

Often in these and other cases, the existence of the new species is brought to the attention of the scientific community 'by' the commercial (aquarium) trade; rather than the other way around. Thus, it is usually not considered so much of a 'problem', but rather a sort of 'symbiotic' relationship between the commercial trade and the taxonomists. Moreover, in such cases in reef fishes, the species has eluded prior discovery not so much because it is rare or has an extremely restricted distribution, but because it simply lives somewhere that scientists have not yet been able to survey. Hence, there are usually few, if any, conservation implications in this context.
____

=== Criteria for determining sensitivity 

The National Biodiversity Network (NBN) in the UK (<<oin,Countryside Agencies OIN 2007>>), and the Department of Environment and Conservation in New South Wales, Australia (<<nsw,Department of Environment and Conservation 2007>>) developed detailed sensitivity criteria, and the previous version of this publication (https://doi.org/10.15468/doc-b02j-gt10[Chapman and Oliver 2008^]) relied heavily on the work of those two agencies. Since the publication of the previous _Guide_, both these agencies (https://www.environment.nsw.gov.au/resources/nature/SensitiveSpeciesPolicyDEC09.pdf[DECCW 2009^], https://nbn.org.uk/the-national-biodiversity-network/archive-information/data-exchange-principles/[NBN 2019a^], https://nbn.org.uk/sensitive-data/[NBN 2019b^], https://www.environment.nsw.gov.au/topics/animals-and-plants/wildlife-management/wildlife-policies-and-guidelines/sensitive-species-data[OEH 2019a^]) along with the South African National Biodiversity Institute (http://biodiversityadvisor.sanbi.org/wp-content/uploads/2012/09/SANBI-Biodiversity-Information-Policy-Series-Digital-Access-to-Sensitive-Taxon.pdf[SANBI 2010^], http://biodiversityadvisor.sanbi.org/wp-content/uploads/2017/06/20160819-NSSL-Workshop-Report.pdf[SANBI 2016^]), the Atlas of Living Australia (https://support.ala.org.au/support/solutions/articles/6000195500-what-is-sensitive-data-[ALA 2018a^]) and others, have given a lot of thought to criteria for determining sensitivity within their jurisdictions. Documentation from all of them have contributed greatly to this document.

A series of criteria for determining the sensitivity of taxa and data along with recommended metadata statements for documenting the reasons for the determination are set out in <<table-01,Table 1>>. The first two are for use by biodiversity data holders and those creating trigger lists of potentially sensitive taxa and refer largely to the taxa themselves. The last two are for use by biodiversity data holders and deal with an assessment of the data they hold and are considering making available—they are not suitable for the creation of trigger lists.

The criteria are used to determine:

[[table-01]]
[caption="Table 1. "]
.Criteria for determining the sensitivity of taxa and data along with recommended metadata statements for documenting the reasons for the determination
|===

| 1. *Risk of harm* | An assessment of whether the taxon is subject to harmful human activity.

| 2. *Impact of harm* | An assessment of the sensitivity of the taxon to the harmful human activity.

| 3. *Sensitivity of data* | An assessment on whether the release of data will increase harm.

| 4. *Decision on release and category of sensitivity* | A balanced decision regarding the release of the data and a determination of the category of sensitivity, and thus the level of generalization, of the data for release.

|===

A set of scenarios using Criteria 1 and 2 above to determine triggers for sensitivity of taxa is attached as an <<annex-01,Annex>> to this document.

The first step in the process of determining sensitivity is to make an assessment on whether or not the taxon is subject to a harmful human activity or not and if the availability of related biodiversity data will increase the likelihood of the harmful activity occurring. 

If it is not then there would appear no reason to list it as a potential environmentally sensitive taxon. It is recommended that you use the documented wording supplied but with additional supporting rational documenting the specifics of the threat, for example: 

[quote]
The taxon is at risk from harmful human activity—it is subject to attack by Phytophthora which is transported by human operated vehicles.

[[table-02]]
[caption="Table 2. "]
.*Risk of harm*: Assessing if the taxon is subject to a harmful human activity
[cols=2*a]
|===

2+^s|1.1. Is the taxon subject to a harmful human activity?

^a|*YES* +
↓ +
Document with supporting rationale using Statement 1a: +
"_The taxon is at risk from a harmful human activity._" +
↓ +
Go to 1.2

^a|*NO* +
↓ +
Document using Statement 1b: +
"_There is no significant risk of a harmful human activity._" +
↓ +
*_Taxon is not sensitive_* +
↓ +
<<table-4,Go to 3>>

2+^s|1.2. Is there established evidence of current or recent occurrences of the harmful human activity?

^a|*YES* +
↓ +
Document with supporting rationale using Statement 1c: +
"_There is established evidence of actual or recent harm to the taxon._" +
↓ +
Go to 1.3

^a|*NO* +
↓ +
Document with supporting rationale using Statement 1d: +
"_There is currently no established evidence of actual harm to the taxon._" +
↓ +
Go to 1.3

2+^s|1.3. Will availability of related biodiversity data increase the likelihood of the harmful human activity taking place?

^a|*YES* +
↓ +
Document with supporting rationale using Statement 1e: +
"_Availability of biodiversity data will increase the likelihood of the harmful human activity taking place._" +
↓ +
<<table-03,Go to 2>>

^a|*NO* +
↓ +
Document with supporting rationale using Statement 1f: +
"_Availability of biodiversity data will not increase the likelihood of the harmful human activity taking place._" +
↓ +
<<table-03,Go to 2>>

|===

The next step is to determine if the taxon is sensitive to that human harm or whether they are suitably robust not to be adversely affected.

[[table-03]]
[caption="Table 3. "]
.*Impact of harm*. Assessing sensitivity of taxa to a harmful human activity.

|===

2+^s|2.1. Does the taxon have characteristics that make it significantly vulnerable to the harmful human activity?

^a|*YES* +
↓ +
Document with supporting rationale using Statement 2a: +
"_The taxon has characteristics that make it significantly vulnerable to the harmful human activity._" +
↓ +
Go to 2.2

^a|*NO* +
↓ +
Document with supporting rationale using Statement 2b: +
"_The taxon is not significantly vulnerable to the harmful human activity._" +
↓ +
Go to 2.2

2+^s|2.2. Is the taxon vulnerable to harmful human activity over its total range, or are there areas (such as in conservation zones, or other parts of the world) where the taxon is not at the same level of risk?

^a|*YES* +
↓ +
Document with supporting rationale using Statement 2c: +
"_The taxon is vulnerable to harmful human activity over its total range."_ +
↓ +
<<table-04,Go to 3>>

^a|*NO* +
↓ +
Document with supporting rationale using Statement 2d: +
_"The taxon is not vulnerable to harmful human activity over its total range *and/or* there are areas where the taxon occurs but is not at significant risk."_ +
↓ +
<<table-04,Go to 3>>

|===

Once it has been decided that the taxon is subject to a significant risk and impact from harm or not, then a decision needs to be taken on whether the release of specific data on that taxon – or other related data – will increase the risk and impact of harm.

[[table-04]]
[caption="Table 4. "]
.*Sensitivity of data*. Assess whether the release of data will increase harm.

|===

2+^s|3.1. Is the content and detail of the biodiversity data such that their release would enable someone to carry out a harmful activity upon the taxon or attribute?

^a|*YES* +
↓ +
Document with supporting rationale using statement 3a: +
_"The content and detail of the data is such that their release would enable someone to carry out a harmful activity upon the taxon or attribute."_ +
↓ +
Go to 3.2

^a|*NO* +
↓ +
*Data are not sensitive* +
Document with supporting rationale using statement 3b: +
_"The content and detail of the data if released would *not* enable someone to carry out a harmful activity upon the taxon or attribute."_ +
↓ +
<<table-05,Go to 4>>

2+^s|3.2. Is information already in the public domain, or already known to those individuals or groups likely to undertake the harmful activity?

^a|*YES* +
↓ +
Document with supporting rationale using statement 3d: +
_"The information is already in the public domain, or is already known to the individuals or groups likely to undertake harmful activities."_ +
↓ +
Go to 3.3

^a|*NO* +
↓ +
Document with supporting rationale using statement 3c: +
_"The information is not in the public domain, and is *not* already known to individuals or groups likely to undertake harmful activities."_ +
↓ +
Go to 3.3

2+^s|3.3. Would disclosure damage a partnership or relationship (especially where the maintenance of which is essential to helping achieve a specific conservation objective)?

^a|*YES* +
↓ +
Document with supporting rationale using statement 3e: +
_"Disclosure of the data is *likely* to damage a partnership or relationship the maintenance of which is essential to helping achieve a specific conservation objective."_ +
↓ +
Go to 3.4

^a|*NO* +
↓ +
Document with supporting rationale using statement 3f: +
_"Disclosure of the data *will not* damage any partnership or relationship essential to conservation."_ +
↓ +
Go to 3.4

2+^s|3.4. Would disclosure allow the locations of sensitive features to be derived through combination with other publicly available information sources?

^a|*YES* +
↓ +
Document with supporting rationale using statement 3g: +
_"Disclosure *would* allow the locations of sensitive features to be derived through combination with other publicly available information sources."_ +
↓ +
<<table-05,Go to 4>>

^a|*NO* +
↓ +
Document with supporting rationale using statement 3h: +
_"Disclosure *will not* allow the locations of sensitive features to be derived through combination with other publicly available information sources."_ +
↓ +
<<table-05,Go to 4>>

|===

The final step is to make an overall assessment based on the three criteria above and to document the overall decision using the combined information documented in making each of the earlier decisions. Once it has been determined that the data should or should not be released, then it is important that a decision is made on the <<Category of sensitivity>>, and the level of <<generalization>> for the release of the data.

[[table-05]]
[caption="Table 5. "]
.*Decision on release and category of sensitivity*. Make a balanced decision regarding the release of data and determining the category and level of generalization.

|=== 

2+^s|4.1. On balance, considering criteria 1 to 3 above and any important wider context, will withholding the information increase the risk of environmental harm or harm to a living person?

^a|*YES* +
↓ +
Document using statement 4a: +
_"On balance, release of the information will, or is likely to, increase the risk of environmental harm or harm to a living person."_ +
↓ +
Go to 4.2 

^a|*NO* +
↓ +
Document using statement 4b: +
_"On balance, release of the data will not increase the risk of environmental harm or harm to a living person."_ +
↓ +
Go to 4.5

2+^s|4.2. Is the taxon distinctive and of high biological significance, under high threat from exploitation/ disease or other identifiable threat where even *general* locality information may threaten the taxon? Or could the release of any part of the record cause *irreparable harm* to the environment or to an individual?

^a|*YES* +
↓ +
Document using statement 4c, collating all supporting rationale and documenting the decision to withhold the data: +
_"The species is a distinctive species of high biological significance, is under high threat from exploitation/ disease or other identifiable threat and even general locality information may threaten the taxon, or the release of the information could cause irreparable harm to the environment, an individual, or some other feature."_ +
*<<cat1,Category 1>>*

^a|*NO* +
↓ +
Go to 4.3

2+^s|4.3. Is the taxon such that the provision of precise locations at finer than 0.1 degrees (~10 km) would subject the taxon to threats such as disturbance and exploitation? Or does the record include highly sensitive information, the release of which could cause *extreme harm* to an individual or the environment?

^a|*YES* +
↓ +
Document using statement 4d, collating all supporting rationale and documenting the decision to release the data: +
_"The species is classed as highly sensitive, and the provision of precise locations would subject the species to threats such as disturbance and exploitation, and/or the record includes highly sensitive information, the release of which could cause extreme harm to the environment or an individual."_ +
*<<cat2,Category 2>>*

^a|*NO* +
↓ +
Go to 4.4

2+^s|4.4. Is the taxon such that the provision of precise locations at finer than 0.01 degrees (~1 km) would subject the species to threats such as collection or deliberate damage? Or does the record include sensitive information, the release of which could cause *harm* to an individual or the environment?

^a|*YES* +
↓ +
Document using statement 4e, collating all supporting rationale and documentubg the decision to release the data: +
_"The species is classed as of medium to high sensitivity, and the provision of precise locations could subject the species to threats such as collection or deliberate damage, and/or the record includes sensitive information, the release of which could cause harm to the environment or to an individual."_ +
*<<cat3,Category 3>>*

^a|*NO* +
↓ +
Go to 4.5

2+^s|4.5. Is the taxon subject to low to medium threat if precise locations (i.e. locations with a precision greater than 0.001 degrees or 100m) become publicly available and where there is some risk of collection or deliberate damage?

^a|*YES* +
↓ +
Document using statement 4f, collate all supporting rationale and document the decision to release the data: +
_"The species is classed as of low to medium sensitivity, and the provision of precise locations could subject the species to threats such as disturbance and exploitation. Detailed data may be made available to individuals under licence."_ +
*<<cat4,Category 4>>*

^a|*NO* +
↓ +
Document using statement 4g, collating all supporting rationale and documenting the decision to release the data: +
_"The species is classed as of low sensitivity, and the distribution of precise locations is unlikely to subject the species to significant threat, and/or the record includes information of low sensitivity, the release of which is unlikely to cause harm to the environment or to any individual. The data should be released to the public ‘as-held’."_ +
*Not Environmentally Sensitive* +
↓ +
Data should be publicly released

|===

In the online survey (https://doi.org/10.35035/vs84-0p13[Chapman 2006^]), a number of respondents identified data awaiting publication, data subject to ongoing research, and incomplete or unchecked data as data that they would class as sensitive, and thus subject to restrictions on release. These are data whose sensitivity has a short time frame and it is important that a time for release or review be clearly documented. They would most likely fall under criterion 3.3 above and would be documented accordingly with the supporting rationale being “awaiting publication”, etc.

NOTE: All data regarded as being sensitive should include a date for review of their sensitivity status, along with documented reasons for the sensitivity status. The date for review may be short or long depending on the nature of the sensitivity.

The <<Categories of sensitivity,categories of sensitivity>> are largely based on those from the NSW Office of Environment and Heritage (https://www.environment.nsw.gov.au/resources/nature/SensitiveSpeciesPolicyDEC09.pdf[DECCW 2009]).

=== Categories of sensitivity

[[table-06]]
[caption="Table 6. "]
.Categories of sensitivity
[options="header"]
|===

| Criterion	| Reasoning

|[[cat1]]*Category 1* +
+ 
Species or records for which no records will be provided at all, or which are only released as present within a large region such as a county, watershed, etc. 

a|The reason for non-disclosure is that: +

. a distinctive species of *high biological significance* is under *high threat* from exploitation/ disease or other identifiable threat where even general locality information may threaten the taxon. +

. the information in the record is of such a nature that its release could cause irreparable harm to the environment, to an individual or to some other feature. +

Data may only be supplied under strict Licence conditions or as presence in a large region such as a watershed, county, or biogeographic region.

|[[cat2]]*Category 2* +

Species or records for which coordinates will be publicly available ‘denatured’ (to 0.1 degrees) and/or other information in the record is generalized. Finer scale data (<<cat3,Category 3>>, <<cat4,Category 4>> or detailed data) may be supplied to individuals under Licence. +

a|The reasons for restriction are that: +

. The species is classed as *highly sensitive*, and the provision of precise locations *would* subject the species to threats such as disturbance and exploitation. +

. The record includes *highly* sensitive information, the release of which could cause *extreme* harm to an individual or to the environment. +

Data are supplied to the public +

. with the georeference denatured to 0.1 degrees (~10 km) and/or +

. with sensitive fields generalized or removed and replaced with suitable replacement wording +

Data may be supplied at finer scales on request under the conditions of a written data agreement, usually a Data Licence Agreement. When data are provided to clients, they will be advised which species or fields  are sensitive and may have their coordinates denatured to that available under <<cat3,Category 3>> or <<cat4,Category 4>>. +

*NB*: In the case where the sensitivity is triggered by fields other than the georeference, it may be more appropriate to class the record as <<cat3,Category 3>> or <<cat4,Category 4>>. +

|[[cat3]]*Category 3* +

Species or records for which coordinates will be publicly available ‘denatured’ (to 0.01 degrees) and/or other information in the record is generalized. Finer scale data (<<cat3,Category 3>>, <<cat4,Category 4>> or detailed data) may be supplied to individuals under Licence.

a|The reasons for restriction are that: +

. The species is classed as of *medium to high sensitivity*, and the provision of precise locations *could* subject the species to threats such as disturbance and exploitation. +

. The record includes *sensitive* information, the release of which could cause harm to an individual or to the environment. +

Data are supplied to the public +

. with the georeference denatured to 0.01 degrees (~ 1 km) and/or +

. with sensitive fields generalized or removed and replaced with suitable replacement wording +

Data may be supplied at finer scales on request under the conditions of a written data agreement, usually a Data Licence Agreement. When data are provided to clients, they will be advised which species or fields are sensitive and may have their coordinates denatured to that available under <<cat4,Category 4>>. +

*NB*: In the case where the sensitivity is triggered by fields other than the georeference, it may be more appropriate to class the record as <<cat4,Category 4>>.

|[[cat4]]*Category 4* +

Species or records for which coordinates will be publicly available ‘denatured’ (to 0.001 degrees) and/or other information in the record is generalized. Detailed ‘as-held’ data may be supplied to individuals under Licence. +

a|The reasons for restriction are that: +

. The species is classed as of *low to medium sensitivity*, and the provision of precise locations could lead to risk of collection or deliberate damage. +

. The record includes *sensitive* information, the release of which could cause harm to an individual or to the environment. +

Detailed data may be supplied under the conditions of a written data agreement, usually a Data Licence Agreement. When data are provided to clients, they will be advised which species or fields are sensitive.

|===
