== Introduction

The unprotected distribution of Sensitive Primary Species Occurrence Data (for example the exact localities of rare, endangered or commercially valuable taxa) was a concern of https://www.gbif.org[GBIF]—the Global Biodiversity Information Facility—from its beginning. The GBIF Secretariat has a vested interest in making data available via its portals, but at the same time respecting the wishes of data providers to restrict information on sensitive taxa. In early 2006, GBIF initiated a process to address this issue, especially in relation to data to be shared through the GBIF network and made visible through https://www.gbif.org[GBIF] and other data aggregating initiatives. 

This resulted in the https://doi.org/10.15468/doc-b02j-gt10^[_Guide to Best Practices for Generalizing Sensitive Primary Species Occurrence Data_]. That document relied heavily on the results of an on-line survey conducted through http://www.surveymonkey.com[Survey Monkey] and subsequent workshops whose reports were originally made available on the GBIF website (Chapman 2006).

A final report on Dealing with Sensitive Primary Species Occurrence Data was developed following these processes and discussions, and was presented to GBIF in April 2007 (Chapman 2007). This report made a number of recommendations, and many of these have been included in this document.

The final step in that process was to develop a _Guide to Best Practices for Primary Species Occurrence Data_ (Chapman and Grafton 2008). That document was proposed as an overriding guideline for institutions, data providers and GBIF Nodes to use to develop their own in-house guidelines. Organizations and institutions were encouraged to produce their own internal documents that incorporated the practices outlined in the _Guide_ and related documents such as the https://doi.org/10.15468/doc-2zpf-zf42[_Guide to Best Practices for Georeferencing_] (Chapman and Wieczorek 2006) and incorporate them into their own working environment. Unfortunately, not as many institutions have taken up the challenge and produced their own internal documents as we had hoped. Two key agencies that have done so, however, are SANBI in South Africa (SANBI 2010) and the Atlas of Living Australia (Tann and Flemons 2009, ALA 2018a) (see <<Implementations>>).

It is also important to understand the possible impact that approaches for restricting sensitive data may have on biodiversity science and, while restricting the availability or resolution of certain data, not overly restricting the uses to which the data may be put. For that reason, a set of principles are elucidated below. Key among these is the need to make biodiversity information freely available wherever possible, in the interests of science, the environment and biodiversity itself. 

NOTE: Words hyperlinked in the text refer to terms that are included in the <<Glossary>>; citations link to sources where they are available online and to the <<References>> where they are not.

=== Objectives

This document aims to provide best practice (or best current practice) for dealing with sensitive primary species occurrence data, and provide guidance on how to make as much data available without at the same time opening up the species to harm because data has been placed in the public domain.

It is now more than a decade since the first _Guide_ was published, and this new publication is designed to bring those practices up to date and to incorporate the experiences gained by institutions that have implemented the _Guide_ in whole or in part. 

=== Audience

This work is designed for those who need, or want to know how they can best make as much data available on sensitive taxa as possible without that published data leading to harm to the species. This document is also for individuals or organizations faced with developing a policy on dealing with sensitive primary species occurrence data and writing in-house documentation consistent with current best practice. 

Above all, this document will help end users of the data to understand the implications of trying to use records that may have been generalized to protect sensitive species, and how to understand the meaning of generalization at different precisions.

=== Scope

The term “best practice” generally refers to the best possible way of doing something. It is commonly used in the fields of business management, software engineering, and medicine, and increasingly in government. The term “*<<current-best-practice,current best practice>>*” (or best current practice) is more specific in that it indicates the possibility for future developments and better practice. Due to the immaturity of this topic, this publication generally refers to “current” best practice and is sure to mature over time as more institutions adopt and adapt the principles outlined herein.

Two issues that this and the previous document have not covered are the issues of the privacy of living individuals and the development of data sharing and Data License Agreements. Both of these issues have legal implications and vary considerably from jurisdiction to jurisdiction. These issues have been covered in detail by others (e.g. <<Corti et al. 2000>>, <<Parry and Mauthner 2004>>, <<GBIF 2017a>>, <<GBIF 2017b>>, <<ALA 2018b>>, <<OEH 2019b>>).

Ethics and biodiversity is a topic that has received little coverage, although for hundreds of years biologists have followed implied ethics in their work. The management of data on sensitive data requires considerable ethical practice and in many cases, a lot of trust and collaboration. Often amateur biologists and citizen scientists are aware of the locations of sensitive taxa, and it is up to the biologists to work with these groups to ensure the continued survival of the species. This won’t always be possible as there will always be rogues, but collaboration can work. For example, working with amateur groups to ethically bring rare plants into cultivation so that there is less pressure on the wild populations.

Archaeology has been grappling with these issues for a long time. As <<Alison Wylie (1996)>> explains, 

[quote]
the foundation of the Society for American Archaeology (SAA) was partially motivated by the desire of academics to distance themselves from amateur archaeologists through the establishment of ethical codes of conduct. One of the main concerns in the field has long been the practice of looting historical sites and the threat this poses to both cultural heritage and future archaeological work. 

Nineteen years later, the archaeologists continue to grapple as pointed out by <<Frank et al. (2015)>> in discussing the results of 62 interviews of archeologists and zoologists conducted by them. They concluded that “Researchers would generally prefer to restrict access to their data from the general public but maintain open data for colleagues”, while realizing the extreme difficulties in managing such a process.

This publication is largely focused on sensitive primary species occurrence data (e.g. museum and herbarium specimen data, observations, images, tracking data) but does have impacts on related data such as population sizes, numbers and viability, habitats and ecosystems, biogeography, traits, bycatch, biosecurity, etc.
